export class Columns{
    name?: string;
    fieldNames?: string;
    fillHeight?: number;
    fieldName?: string;
    type?: string;
    dataType?: string;
    width?: string;
    styles?: object;
    header?: object;
    footer?: object;
    button?: string;
    styleCallback?: object;
    renderer?: any;
    popUpObject?: any;
    editor?: object;
    lookupDisplay?: boolean;
    styleName?: string;
    placeHolder?: string;
    values?: object;
    labels?: object;
    widget?: object;
    mask?: any;
    datetimeFormat?: any;
    numberFormat?: any;
};
