export class Columns{
    name?: string;
    fieldName: string;
    type?: string;
    dataType?: string;
    width?: string;
    styles?: object;
    header?: object;
    button?: string;
    styleCallback?: object;
    renderer?: object;
    editor?: object;
    lookupDisplay?: boolean;
    styleName?: string;
    placeHolder?: string;
    values?: object;
    labels?: object;
    widget?: object;
    numberFormat?: any;
};
